spring.application.name=panda-cloud-eureka-register-center
server.port=8082
server.servlet.context-path=/panda-cloud/eureka/
#SpringCloud Eureka Security配置
spring.profiles.default=default
spring.profiles.active=application-standalone.yml
spring.security.user.name=admin
spring.security.user.password=PandaCloud@2021

#SpringCloud Eureka Instance配置
eureka.instance.hostname=localhost
eureka.instance.registry.default-open-for-traffic-count=120
eureka.instance.lease-expiration-duration-in-seconds=20
eureka.instance.lease-renewal-interval-in-seconds=20
eureka.instance.prefer-ip-address=true
eureka.instance.instance-enabled-onit=true
eureka.instance.home-page-url=${eureka.instance.hostname}:${server.port}
eureka.instance.home-page-url-path=${server.servlet.context-path}
eureka.instance.registry.expected-number-of-clients-sending-renews=10
eureka.instance.instance-id=${eureka.instance.hostname}:${server.port}@${random.long(1000000,9999999)}
eureka.instance.health-check-url=${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}
eureka.instance.health-check-url-path=/actuator/health
#SpringCloud Eureka Server配置
eureka.server.peer-node-connect-timeout-ms=60000
eureka.server.peer-node-read-timeout-ms=60000
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000
eureka.server.use-read-only-response-cache=false
eureka.server.registry-sync-retries=6000
eureka.server.registry-sync-retry-wait-ms=6000
eureka.server.renewal-percent-threshold=0.49
eureka.server.batch-replication=true
eureka.server.expected-client-renewal-interval-seconds=6000
eureka.server.g-zip-content-from-remote-region=true
#SpringCloud Eureka Client配置
eureka.client.service-url.default-zone=http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.region=region-east-1

management.endpoints.web.exposure.exclude=*
management.endpoint.health.show-details=always


