
spring.application.name=panda-cloud-zuul-gateway-center
server.port=8081

eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.allow-redirects=true


zuul.add-host-header=true
zuul.host.connect-timeout-millis=60000
zuul.host.max-per-route-connections=128
zuul.host.socket-timeout-millis=60000
zuul.host.time-to-live=128
zuul.retryable=true